import os

# MySQL
HOSTNAME = '127.0.0.1'
PORT = '3306'
DATABASE = 'steganalysis'
USERNAME = 'root'
PASSWORD = '123456'
DB_URI = 'mysql+pymysql://{}:{}@{}:{}/{}'.format(USERNAME, PASSWORD, HOSTNAME, PORT, DATABASE)
SQLALCHEMY_DATABASE_URI = DB_URI

SQLALCHEMY_TRACK_MODIFICATIONS = True

# Mail Config
MAIL_SERVER = ''
MAIL_PROT = 80
MAIL_USERNAME = ""
MAIL_PASSWORD = ""
MAIL_DEFAULT_SENDER = ""

# Qiniu Config
QINIU_AK = ""
QINIU_SK = ""
QINIU_BUCKET_NAME = ""
QINIU_URL = ""

# Secret Key
SECRET_KEY = '1234565'
